services:
  backend:
    build: .
    container_name: product-backend
    ports:
        - "8080:8080"
        - "5005:5005"
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/product
        - SPRING_DATASOURCE_USERNAME=product-user
        - SPRING_DATASOURCE_PASSWORD=product-user-password
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
        - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
    depends_on:
        - db
  db:
   image: postgres:14
   container_name: product-db
   restart: always
   environment:
     POSTGRES_DB: product
     POSTGRES_USER: product-user
     POSTGRES_PASSWORD: product-user-password
   volumes:
      - product-data://var/lib/postgresql/data
volumes:
  product-data:
